
export const GET_COMAND_REQUEST = 'GET_COMAND_REQUEST'
export const GET_COMAND_SUCCESS = 'GET_COMAND_SUCCESS'
export const GET_COMAND_FAIL = 'GET_COMAND_FAIL'

export const ADD_COMANDSTATUS_SUCCESS = 'ADD_COMANDSTATUS_SUCCESS'
export const ADD_COMANDSTATUS_REQUEST = 'ADD_COMANDSTATUS_REQUEST'
export const ADD_COMANDSTATUS_FAIL = 'ADD_COMANDSTATUS_FAIL'
export const ADD_COMANDSTATUS_RESET = 'ADD_COMANDSTATUS_RESET'



export const UPDATE_COMANDSTATUS_SUCCESS = 'UPDATE_COMANDSTATUS_SUCCESS'
export const UPDATE_COMANDSTATUS_REQUEST = 'UPDATE_COMANDSTATUS_REQUEST'
export const UPDATE_COMANDSTATUS_FAIL = 'UPDATE_COMANDSTATUS_FAIL'
export const UPDATE_COMANDSTATUS_RESET = 'UPDATE_COMANDSTATUS_RESET'


export const COMAND_DELETE_REQUEST = 'COMAND_DELETE_REQUEST'
export const COMAND_DELETE_SUCCESS = 'COMAND_DELETE_SUCCESS'
export const COMAND_DELETE_FAIL = 'COMAND_DELETE_FAIL'



