
export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL'

export const ADD_PRODUCTSTATUS_SUCCESS = 'ADD_PRODUCTSTATUS_SUCCESS'
export const ADD_PRODUCTSTATUS_REQUEST = 'ADD_PRODUCTSTATUS_REQUEST'
export const ADD_PRODUCTSTATUS_FAIL = 'ADD_PRODUCTSTATUS_FAIL'
export const ADD_PRODUCTSTATUS_RESET = 'ADD_PRODUCTSTATUS_RESET'



export const UPDATE_PRODUCTSTATUS_SUCCESS = 'UPDATE_PRODUCTSTATUS_SUCCESS'
export const UPDATE_PRODUCTSTATUS_REQUEST = 'UPDATE_PRODUCTSTATUS_REQUEST'
export const UPDATE_PRODUCTSTATUS_FAIL = 'UPDATE_PRODUCTSTATUS_FAIL'
export const UPDATE_PRODUCTSTATUS_RESET = 'UPDATE_PRODUCTSTATUS_RESET'


export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const PRODUCT_UPDATE_PROFILE_REQUEST = 'PRODUCT_UPDATE_PROFILE_REQUEST'
export const PRODUCT_UPDATE_PROFILE_SUCCESS = 'PRODUCT_UPDATE_PROFILE_SUCCESS'
export const PRODUCT_UPDATE_PROFILE_FAIL = 'PRODUCT_UPDATE_PROFILE_FAIL'
export const PRODUCT_UPDATE_PROFILE_RESET = 'PRODUCT_UPDATE_PROFILE_RESET'
